// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsCollectionsOps "github.com/acme-kuetix/acme-std-collections/modules/collections/ops/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["collections/ops"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"collections/ops"+"/"+"ops", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "ops", Impl: transitionsCollectionsOps.NewOpsTransitions() }})
	}
}
